# Gesture Recognition (Subsystem 2)

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report
from  sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import tensorflow as tf
from tensorflow import keras
import sklearn
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import confusion_matrix

## Reading 'Dataset_Subsystem_2.csv' as Pandas Dataframe

In [23]:
data = pd.read_csv('Dataset_Subsystem_2.csv')
data["label"]=data["camera_facing_side"]+data["gesture"]
del data["ID"]
del data["frame"]
del data["camera_facing_side"]
del data["gesture"]
data.head()

palm_root_x  palm_root_y  palm_thumb_1_x  palm_thumb_1_y  palm_thumb_2_x  \
0          494          295             412             266             376   
1          493          294             410             266             375   
2          493          294             409             267             374   
3          492          294             407             267             373   
4          491          294             405             267             373   

   palm_thumb_2_y  palm_thumb_3_x  palm_thumb_3_y  palm_index_1_x  \
0             243             346             225             434   
1             243             345             225             433   
2             243             344             225             432   
3             243             343             225             431   
4             243             342             225             430   

   palm_index_1_y  ...  dorsal_ring_4_y  dorsal_pinky_1_x  dorsal_pinky_1_y  \
0             186  ...                0                 0                 0   
1             185  ...                0                 0                 0   
2             185  ...                0                 0                 0   
3             184  ...                0                 0                 0   
4             183  ...                0                 0                 0   

   dorsal_pinky_2_x  dorsal_pinky_2_y  dorsal_pinky_3_x  dorsal_pinky_3_y  \
0                 0                 0                 0                 0   
1                 0                 0                 0                 0   
2                 0                 0                 0                 0   
3                 0                 0                 0                 0   
4                 0                 0                 0                 0   

   dorsal_pinky_4_x  dorsal_pinky_4_y     label  
0                 0                 0  openpalm  
1                 0                 0  openpalm  
2                 0                 0  openpalm  
3                 0                 0  openpalm  
4                 0                 0  openpalm  

[5 rows x 81 columns]

In [24]:
number=LabelEncoder()
data["label"] = number.fit_transform(data["label"].astype(str))
data.head()

palm_root_x  palm_root_y  palm_thumb_1_x  palm_thumb_1_y  palm_thumb_2_x  \
0          494          295             412             266             376   
1          493          294             410             266             375   
2          493          294             409             267             374   
3          492          294             407             267             373   
4          491          294             405             267             373   

   palm_thumb_2_y  palm_thumb_3_x  palm_thumb_3_y  palm_index_1_x  \
0             243             346             225             434   
1             243             345             225             433   
2             243             344             225             432   
3             243             343             225             431   
4             243             342             225             430   

   palm_index_1_y  ...  dorsal_ring_4_y  dorsal_pinky_1_x  dorsal_pinky_1_y  \
0             186  ...                0                 0                 0   
1             185  ...                0                 0                 0   
2             185  ...                0                 0                 0   
3             184  ...                0                 0                 0   
4             183  ...                0                 0                 0   

   dorsal_pinky_2_x  dorsal_pinky_2_y  dorsal_pinky_3_x  dorsal_pinky_3_y  \
0                 0                 0                 0                 0   
1                 0                 0                 0                 0   
2                 0                 0                 0                 0   
3                 0                 0                 0                 0   
4                 0                 0                 0                 0   

   dorsal_pinky_4_x  dorsal_pinky_4_y  label  
0                 0                 0      3  
1                 0                 0      3  
2                 0                 0      3  
3                 0                 0      3  
4                 0                 0      3  

[5 rows x 81 columns]

In [25]:
data.iloc[528]

palm_root_x         0
palm_root_y         0
palm_thumb_1_x      0
palm_thumb_1_y      0
palm_thumb_2_x      0
                   ..
dorsal_pinky_3_x    0
dorsal_pinky_3_y    0
dorsal_pinky_4_x    0
dorsal_pinky_4_y    0
label               0
Name: 528, Length: 81, dtype: int64

In [26]:
classes = {0:"fistdorsal", 1:"fistpalm", 2:"opendorsal", 3:"openpalm", 4:"threefingersdorsal", 5:"threefingerspalm"}

##  Assigning the input data and labels to x and y

In [27]:
X=np.asarray(data.loc[:, data.keys()[0:80]])
Y=np.asarray(data["label"])

#x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

## Normalization

In [28]:
def standardize(x):
    scaled = StandardScaler()
    x = scaled.fit_transform(x)
    return(x)

## Cross Validation

## Normal Split (70:30)

In [29]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
encoder = sklearn.preprocessing.OneHotEncoder(dtype=np.float32)
encoder.fit(y_train.reshape((-1, 1)))

y_train_encoded = encoder.transform(y_train.reshape((-1, 1))).toarray()
y_test_encoded = encoder.transform(y_test.reshape((-1, 1))).toarray()
y_test_encoded

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]], dtype=float32)

## Logistic Regression 

In [45]:
print('X_train.shape: ', x_train.shape, '\n X_test.shape: ', x_test.shape)
print('y_train.shape: ', y_train.shape, '\n y_test.shape: ', y_test.shape)
clf = LogisticRegression(penalty='l1', C=100, solver='liblinear')
clf.fit(x_train, y_train)
print('Test accuracy:', clf.score(x_test, y_test))

X_train.shape:  (49775, 80) 
 X_test.shape:  (12444, 80)
y_train.shape:  (49775,) 
 y_test.shape:  (12444,)
Test accuracy: 1.0


## ML Model

In [31]:
def get_compiled_model():
    model = keras.Sequential([
    keras.layers.Dense(10, activation='relu'),
    keras.layers.Dense(6)
])

    model.compile(optimizer='adam',
                loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                metrics=['accuracy'])
    return model


In [32]:
model = get_compiled_model()
model.fit(x_train,y_train,epochs=7)

Train on 49775 samples
Epoch 1/7
49775/49775 [==============================] - 2s 41us/sample - loss: 1.2703 - accuracy: 0.9280
Epoch 2/7
49775/49775 [==============================] - 2s 34us/sample - loss: 0.0980 - accuracy: 0.9805
Epoch 3/7
49775/49775 [==============================] - 2s 34us/sample - loss: 0.0390 - accuracy: 0.9913
Epoch 4/7
49775/49775 [==============================] - 2s 33us/sample - loss: 0.0282 - accuracy: 0.9924
Epoch 5/7
49775/49775 [==============================] - 2s 34us/sample - loss: 0.0172 - accuracy: 0.9970
Epoch 6/7
49775/49775 [==============================] - 2s 34us/sample - loss: 0.0091 - accuracy: 0.9972
Epoch 7/7
49775/49775 [==============================] - 2s 34us/sample - loss: 0.0022 - accuracy: 0.9999


In [33]:
test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print('Test accuracy: {:2.2f}%'.format(test_accuracy*100))
prediction = model.predict(x_test)

Test accuracy: 100.00%


In [34]:
prediction

array([[ 105.256386  ,  213.2424    ,   95.25954   ,  -29.602812  ,
        -218.20049   ,   -7.383878  ],
       [  63.319603  ,   39.054848  ,  109.0839    , -103.43826   ,
          33.129345  ,  251.66284   ],
       [  62.868866  ,  -56.759174  , -258.26614   ,  183.45058   ,
          93.3043    ,  122.968185  ],
       ...,
       [  -1.6804547 ,   11.523974  ,   17.171097  ,   -6.4915457 ,
         -17.520985  ,    2.1765556 ],
       [ 111.296104  ,   82.08705   ,   -0.37081218,    1.462051  ,
         -10.272417  ,  -21.572626  ],
       [ -10.795582  ,  261.84317   ,  257.11078   ,  -94.691086  ,
        -321.41022   ,   67.96891   ]], dtype=float32)

In [35]:
y_pred=[]
for i in range(len(prediction)):
    predicted_label=np.argmax(prediction[i])
    y_pred.append(predicted_label)

In [36]:
y_pred_1=np.array(y_pred)
encoder.fit(y_pred_1.reshape((-1, 1)))
y_pred_encoded = encoder.transform(y_pred_1.reshape((-1, 1))).toarray()

In [37]:
y_pred_encoded

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       ...,
       [0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.]], dtype=float32)

## Classification Report

In [38]:
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [10, 10]

In [39]:
labels = ["fist dorsal", "fist palm", "open dorsal", "open palm", "three fingers dorsal", "three fingers palm"]
print(classification_report(y_test_encoded, y_pred_encoded, target_names=labels))
#plt.show()

                      precision    recall  f1-score   support

         fist dorsal       1.00      1.00      1.00      2095
           fist palm       1.00      1.00      1.00      1967
         open dorsal       1.00      1.00      1.00      2147
           open palm       1.00      1.00      1.00      2186
three fingers dorsal       1.00      1.00      1.00      2097
  three fingers palm       1.00      1.00      1.00      1952

           micro avg       1.00      1.00      1.00     12444
           macro avg       1.00      1.00      1.00     12444
        weighted avg       1.00      1.00      1.00     12444
         samples avg       1.00      1.00      1.00     12444



## Confusion Matrix

In [52]:
from sklearn.metrics import multilabel_confusion_matrix
import matplotlib.pyplot as plt
from mlxtend.evaluate import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

cm = multilabel_confusion_matrix(y_test, y_pred_1)
cm[5]

array([[10492,     0],
       [    0,  1952]], dtype=int64)